"""Ports used by the persistence-free Creation Module orchestrator."""

from typing import Protocol, Sequence

from creation_module.models import CategorizationProposal, KnowledgeSource, MemoryBrickProposal, MetadataLayer, SourceCategorization
from creation_module.workspace_models import WorkspaceCreationRequest


class KnowledgeSourceService(Protocol):
    def get_source(self, source_id: str) -> KnowledgeSource: ...
    def update_metadata(self, *, source_id: str, expected_source_hash: str, updates: dict[MetadataLayer, str], generated: bool) -> KnowledgeSource: ...
    def update_categorization(self, *, source_id: str, expected_source_hash: str, categorization: SourceCategorization) -> KnowledgeSource: ...
    def validate_categorization(self, categorization: SourceCategorization) -> SourceCategorization: ...


class MemoryProposalService(Protocol):
    def create_memory_from_proposal(self, proposal: MemoryBrickProposal) -> object: ...


class WorkspaceCreationService(Protocol):
    """Core-composed port that owns workspace persistence and graph projection."""

    def create_sheet(self, request: WorkspaceCreationRequest) -> object: ...
    def create_comment(self, request: WorkspaceCreationRequest) -> object: ...
    def create_memory(self, request: WorkspaceCreationRequest) -> object: ...


class CreationGenerator(Protocol):
    def generate_metadata(self, source: KnowledgeSource, layers: Sequence[MetadataLayer]) -> dict[MetadataLayer, str]: ...
    def categorize_source(self, source: KnowledgeSource) -> CategorizationProposal: ...
    def propose_memory_bricks(self, source: KnowledgeSource) -> list[MemoryBrickProposal]: ...
    def generate_workspace_fields(self, kind: str, request: str, fields: Sequence[str]) -> dict[str, str]: ...
